name: pydata
channels:
  - damianavila82
  - defaults
dependencies:
  - matplotlib=2.2.2
  - nb_conda_kernels
  - numpy=1.14.2
  - pillow=5.1.0
  - python=3.6.5
  - seaborn=0.8.1
  - pip:
    - keras==2.1.6
    - tensorflow==1.8.0
